### ISSUE TITLE
Misleading/incorrect element selectors in documentation

### ISSUE THREAD

**Issue by juhamust** [alexyoung/ico#14]
The project home page shows few graph examples, like:

``` javascript
new Ico.BarGraph($('bargraph'), { one: $random(1, 25) }, { bar_labels: true });
```

Unfortunatelly, the selector used in examples is incorrect/does not work: element selector returns either empty list or multiple entries while simple element is expected. This confuses the users (like me!) trying to use library at first.

The reason why the actual graphs are shown is because `document.getElementById` is used instead. 
Thus, in examples,  use either:
- jQuery: `$('#bargraph')[0]`
- Javascript: `document.getElementById('bargraph')`

**Comment by alexyoung** [comment]
Yeah, my examples had some custom code I wrote for `$` and `$random` that I completely forgot I about.  I'll rewrite it soon.

**Comment by alexyoung** [comment]
I'll try making it support jQuery objects as well by doing `this.element = element.length ? element[0] : element;`.  I'm not sure if this is the best solution -- I could also detect `$('#selector').jquery`.
