### ISSUE TITLE
Ability to set each bar on a bar graph to a different colour

### ISSUE THREAD

**Issue by theycallmeswift** [alexyoung/ico#15]
Right now the entire graph has to be one colour.  Would be sweet if I could just pass in an array for colours and have each bar be the corresponding color.

**Comment by uiteoi** [comment]
Rule #3 Use color only when needed to serve a particular communication goal.
Rule #4 Use different colors only when they correspond to differences of meaning in the data.

http://www.perceptualedge.com/articles/visual_business_intelligence/rules_for_using_color.pdf

**Comment by alexyoung** [comment]
You can use multiple colours in the "grouped" charts, which essentially corresponds with those rules you posted

**Comment by theycallmeswift** [comment]
Yeah, but you lose the ability to put a label under each bar with the grouping

The color actually works fine in my case.  The bars are events ordered by time from right to left.  The problem is that some of them are bad events and need to be easily identified at a glance. So, I thought making them a light shade of red and keeping the rest green would work fine.

**Comment by theycallmeswift** [comment]
Just saw this today.  Thanks for fixing it!

**Comment by alexyoung** [comment]
:)
