### ISSUE TITLE
Line graph build fails if all values match due to step == 0

### ISSUE THREAD

**Issue by mikec83** [alexyoung/ico#4]
If you build a line graph with all of the Y values lining up to be the exact same thing, Ico fails in longestLabel() due to the labels variable having a length of 0.  Seems this is because the for loop in the makeValueLabels() never runs because step == 0

**Comment by alexyoung** [comment]
I'll take a look

**Comment by dgilperez** [comment]
Just wanted to say thanks !!! I was just struggling with this right now ...
