### ISSUE TITLE
Ico extends Array.prototype…

### ISSUE THREAD

**Issue by mikl** [alexyoung/ico#5]
This is not a bug, but extending `Array.prototype` tends to cause unexpected issues with other libraries. If everyone wrote their JavaScript properly, this would not be as big a problem, but `for (val in myArray)` without checking `hasOwnAttribute` is a common sight, and Ico’s extentions causes these scripts to fall over and die.

These scripts should be fixed, but if you’re working on a client’s site, you may not be able to do so easily, if at all (it might be outside your control), so it makes it a lot less certain that Ico can easily be implemented on legacy sites.

**Comment by alexyoung** [comment]
I just did it out of sheer laziness when I migrated away from using a framework (years ago Ico used Prototype).  Thanks for reminding me to sort this out!

**Comment by mikl** [comment]
Wow, that was fast – thank you :)
