### ISSUE TITLE
Raphael 2.0?

### ISSUE THREAD

**Issue by adaburrows** [alexyoung/ico#9]
Has this library been updated to use Raphael 2.0? Or, does it require the older version? I haven't tested it with the new version of Raphael, but wanted to ask if you were aware of any problems. Thanks.

**Comment by alexyoung** [comment]
I can't remember if I updated/tested it, I'll add this to my to-do list

**Comment by alexyoung** [comment]
I just tested `docs/examples.html` and it seems to work fine with Raphael 2.0.  I think remember the Raphael author saying 2.0 wasn't going to introduce major API changes.

**Comment by adaburrows** [comment]
Fantastic. Thanks. I'll post another update to my blog post that consistently gets at least thirty visits a day -- it's about g.line.js from gRaphael, but I link to you as a better option for line charts. ;-)
